version: '3.9'

services:
  alertmanager:
    image: 'alertmanager:v1'
    ports:
      - '9093:9093'
    restart: unless-stopped
    volumes:
      - '../alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro'
      - 'alertmanager_data:/alertmanager'
    networks:
      - monitoring

  blackbox-exporter:
    image: 'blackbox:v1'
    ports:
      - '9115:9115'
    restart: unless-stopped
    volumes:
      - './prometheus/blackbox.yml:/etc/blackbox_exporter/config.yml:ro'
    command:
      - '--config.file=/etc/blackbox_exporter/config.yml'
    cap_add:
      - NET_RAW
    networks:
      - monitoring

  cadvisor:
    image: 'gcr.io/cadvisor/cadvisor:v0.47.0'
    ports:
      - '8080:8080'
    restart: unless-stopped
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:ro'
      - '/sys:/sys:ro'
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
    networks:
      - monitoring

  grafana:
    image: 'grafana:v1'
    user: root
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=yourpassword
    ports:
      - '3000:3000'
    restart: unless-stopped
    volumes:
      - '../grafana/grafana_data:/var/lib/grafana'
      - '../grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro'
      - '../grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro'
      - '../grafana/dashboards:/var/lib/grafana/dashboards:ro'
    networks:
      - monitoring

  node-exporter:
    image: 'node-exporter:v1'
    command: >-
      --path.procfs=/host/proc --path.sysfs=/host/sys
      --collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)
    ports:
      - '9100:9100'
    restart: unless-stopped
    volumes:
      - '/proc:/host/proc:ro'
      - '/sys:/host/sys:ro'
      - '/:/rootfs:ro'
    networks:
      - monitoring

  prometheus:
    image: 'prometheus:v1'
    ports:
      - '9090:9090'
    restart: unless-stopped
    volumes:
      - './prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro'
      - './prometheus/rules:/etc/prometheus/rules:ro'
      - 'prometheus_data:/prometheus'
    networks:
      - monitoring

  loki:
    image: 'loki:v1'
    user: root
    command: '-config.file=/etc/loki/local-config.yaml'
    ports:
      - '3100:3100'
    restart: unless-stopped
    volumes:
      - '../loki/loki-config.yaml:/etc/loki/local-config.yaml:ro'
      - '../loki/index:/loki/index'
      - '../loki/cache:/loki/cache'
      - '../loki/chunks:/loki/chunks'
      - '../loki/wal:/loki/wal'
    networks:
      - monitoring

volumes:
  alertmanager_data:
  grafana_data:
  prometheus_data:

networks:
  monitoring:
    driver: bridge
