global:
  scrape_interval: 30s
  evaluation_interval: 30s
  external_labels:
    monitor: prom

rule_files:
  - /etc/prometheus/rules/*.rules

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: node-exporter
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: blackbox_exporter
    static_configs:
      - targets: ['blackbox-exporter:9115']

  - job_name: blackbox-ping
    scrape_interval: 30s
    metrics_path: /probe
    params:
      module: [icmp_ipv4]
    static_configs:
      - targets:
          - 8.8.8.8
          - google.com
          - node-exporter
          - blackbox-exporter
          - cadvisor
          - alertmanager
          - grafana
          - prometheus
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: blackbox-http
    scrape_interval: 30s
    metrics_path: /probe
    params:
      module: [http_advanced]
    static_configs:
      - targets:
          - http://google.com
          - http://github.com
          - http://example.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: blackbox-tcp
    scrape_interval: 30s
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
      - targets:
          - google.com:443
          - github.com:443
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: grafana
    scrape_interval: 30s
    metrics_path: /metrics
    static_configs:
      - targets: ['grafana:3000']

  - job_name: alertmanager
    scrape_interval: 30s
    metrics_path: /metrics
    static_configs:
      - targets: ['alertmanager:9093']

  - job_name: loki
    scrape_interval: 30s
    metrics_path: /metrics
    static_configs:
      - targets: ['loki:3100']

