---
- name: Find real resolv.conf path if it's a symlink
  stat:
    path: /etc/resolv.conf
    follow: yes
  register: resolvconf_stat

- name: Set DNS servers
  become: yes
  copy:
    dest: "{{ resolvconf_stat.stat.path }}"
    content: |
      nameserver 178.22.122.100
      nameserver 185.51.200.2
  notify: restart networking
