modules:
  icmp_ipv4:
    prober: icmp
    timeout: 10s
    icmp:
      preferred_ip_protocol: "ip4"

  http_advanced:
    prober: http
    timeout: 10s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2"]
      valid_status_codes: [200,201,202,203,204,205,206,207,208,226,300,301,302,303,304,305,306,307,308]
      method: GET
      no_follow_redirects: false
      fail_if_ssl: false
      fail_if_not_ssl: false
      tls_config:
        insecure_skip_verify: true

  tcp_connect:
    prober: tcp
    timeout: 5s
    tcp: {}

  dns_lookup:
    prober: dns
    timeout: 5s
    dns:
      query_name: "www.google.com"
      query_type: "A"
      valid_rcodes: ["NOERROR"]

