all:
  children:
    server:
      hosts:
        monitoring_stack:
          ansible_host: #192.168.1.100  # Replace with the target server's IP address or hostname
          ansible_user: root          # SSH user to connect to the remote server
          ansible_become: true        # Enables privilege escalation (e.g., sudo)

    # local:
    #   hosts:
    #     localhost:
    #       ansible_connection: local
    #       # This section defines a local host for running Ansible tasks directly on the control machine.
    #       # It's useful if you want to test or install components on your own machine without using SSH.
